--------------------------------------------------------
--  已建立檔案 - 星期二-六月-20-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISCOUNT
--------------------------------------------------------

  CREATE TABLE "MSH"."DISCOUNT" 
   (	"ID_DISCOUNT" NUMBER(15,0), 
	"TYPE_DISCOUNT" VARCHAR2(20 BYTE), 
	"AMOUNT_DISCOUNT" NUMBER(15,4), 
	"NAME_DISCOUNT" VARCHAR2(100 BYTE), 
	"ENABLE_DISCOUNT" NUMBER(*,0), 
	"CREATEDATE_DISCOUNT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSH"."DISCOUNT_PK" ON "MSH"."DISCOUNT" ("ID_DISCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DISCOUNT
--------------------------------------------------------

  ALTER TABLE "MSH"."DISCOUNT" MODIFY ("ID_DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "MSH"."DISCOUNT" ADD CONSTRAINT "DISCOUNT_PK" PRIMARY KEY ("ID_DISCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
