--------------------------------------------------------
--  已建立檔案 - 星期六-七月-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALESLESS
--------------------------------------------------------

  CREATE TABLE "MSH"."SALESLESS" 
   (	"RECEIPTNO_SALESLESS" VARCHAR2(20 BYTE), 
	"ID_SALESLESS" NUMBER(38,0), 
	"NAME_SALESLESS" VARCHAR2(100 BYTE), 
	"AMOUNT_SALESLESS" NUMBER(15,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALESLESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSH"."SALESLESS_PK" ON "MSH"."SALESLESS" ("RECEIPTNO_SALESLESS", "ID_SALESLESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALESLESS
--------------------------------------------------------

  ALTER TABLE "MSH"."SALESLESS" ADD CONSTRAINT "SALESLESS_PK" PRIMARY KEY ("RECEIPTNO_SALESLESS", "ID_SALESLESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MSH"."SALESLESS" MODIFY ("ID_SALESLESS" NOT NULL ENABLE);
  ALTER TABLE "MSH"."SALESLESS" MODIFY ("RECEIPTNO_SALESLESS" NOT NULL ENABLE);
