--------------------------------------------------------
--  已建立檔案 - 星期五-六月-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANS
--------------------------------------------------------

  CREATE TABLE "MSH"."TRANS" 
   (	"AMOUNT_TRANS" NUMBER(20,0), 
	"RECEIPTNO_TRANS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSH"."TRANS_PK" ON "MSH"."TRANS" ("RECEIPTNO_TRANS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRANS
--------------------------------------------------------

  ALTER TABLE "MSH"."TRANS" MODIFY ("RECEIPTNO_TRANS" NOT NULL ENABLE);
  ALTER TABLE "MSH"."TRANS" ADD CONSTRAINT "TRANS_PK" PRIMARY KEY ("RECEIPTNO_TRANS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
